# Set the Docker Compose file format.
version: "3.7"

# Define the services (containers) that make up the project. For those services
# with an entry point not designed to function as PID 1, we tell Docker to use
# its own init process.
services:
  mutagen:
    build: ./mutagen
    init: true
    container_name: web-go-mutagen
    volumes:
      - code:/code
  database:
    build: ./database
  api:
    build: ./api
    environment:
      DATABASE_URL: "postgres://messagessvc:InSeCUr3Dem0PasS@database:5432/messagesdb?sslmode=disable"
      SERVER_BIND: ":8081"
      CORS_ORIGIN: "http://localhost:8080"
    volumes:
      - code:/code
  frontend:
    build: ./frontend
    init: true
    environment:
      OUTPUT_PATH: "/code/build"
    volumes:
      - code:/code
  web:
    build: ./web
    environment:
      SERVER_ROOT: "/code/build"
      SERVER_BIND: ":8080"
    volumes:
      - code:/code

# Create a volume to store and share synchronized code.
volumes:
  code:
